# Generated by Django 6.0.3 on 2026-04-15 06:52

from django.contrib.auth.hashers import make_password
from django.db import migrations


SEED_USERS = [
    {
        'username': 'admin_soc',
        'password': 'Admin@2025',
        'email': 'admin@soc.local',
        'is_staff': True,
        'role': 'admin',
    },
    {
        'username': 'jacobo',
        'password': 'Jacobo@2025',
        'email': 'jacobo@soc.local',
        'is_staff': False,
        'role': 'analyst_n1',
    },
]


def seed_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')

    for data in SEED_USERS:
        user, created = User.objects.get_or_create(username=data['username'])
        if created:
            user.password = make_password(data['password'])
            user.email = data['email']
            user.is_staff = data['is_staff']
            user.is_active = True
            user.save()

        UserProfile.objects.update_or_create(
            user=user,
            defaults={'role': data['role']},
        )


def unseed_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username__in=[d['username'] for d in SEED_USERS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_simplify_roles'),
    ]

    operations = [
        migrations.RunPython(seed_users, reverse_code=unseed_users),
    ]
