# Generated by Django 6.0.3 on 2026-04-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_default_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('analyst_n1', 'Analista Nivel 1'), ('analyst_n2', 'Analista Nivel 2')], default='analyst_n1', max_length=20),
        ),
    ]
