# -*- coding: utf-8 -*-
"""Modelo final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sA50z0CfbsWr7VlgEQuMOuv_428L4CRU
"""

import pandas as pd

import numpy as np

from google.colab import files

uploaded = files.upload()

"""## Carga de datos"""

import pandas as pd
# Cambia el nombre si fuera necesario
file_name = "microsoft_train_dataset_final.csv"
df = pd.read_csv(file_name)
print("Dimensiones iniciales:", df.shape)
display(df.head())
print(df.columns.tolist())

print("\nTipos de datos:")
print(df.dtypes)

print("\nValores nulos por columna:")
print(df.isnull().sum())

print("\nDuplicados exactos:", df.duplicated().sum())

print("\nDistribución de label:")
print(df["label"].value_counts(dropna=False))

"""## Limpieza de datos"""

# Copia de seguridad
df_clean = df.copy()

# Normalizar nombres de columnas
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# Eliminar duplicados
df_clean = df_clean.drop_duplicates()

# Limpiar espacios en texto
for col in df_clean.select_dtypes(include="object").columns:
    df_clean[col] = df_clean[col].astype(str).str.strip()

print("Dimensiones luego de limpieza básica:", df_clean.shape)

"""## Feature engineering"""

cols_clave = [
    "severity",
    "mitre_tactic",
    "attack_type",
    "event_category",
    "label"
]

for col in cols_clave:
    print(f"\n--- {col} ---")
    print(df_clean[col].value_counts(dropna=False).head(20))

# Pasar a minúsculas donde convenga
for col in [
    "severity", "protocol", "traffic_type", "event_category",
    "attack_type", "mitre_tactic", "kill_chain_stage",
    "log_source", "ids_ips_alert", "firewall_action",
    "malware_indicator", "asset_criticality"
]:
    if col in df_clean.columns:
        df_clean[col] = df_clean[col].astype(str).str.lower().str.strip()

print("Dimensiones luego de validar etiquetas:", df_clean.shape)
print(df_clean["label"].value_counts())

num_cols = df_clean.select_dtypes(include=[np.number]).columns
cat_cols = df_clean.select_dtypes(include=["object"]).columns

for col in num_cols:
    df_clean[col] = df_clean[col].fillna(df_clean[col].median())

for col in cat_cols:
    df_clean[col] = df_clean[col].fillna("unknown")

print(df_clean.isnull().sum().sum(), "valores nulos restantes")

# intentos fallidos no negativos
if "failed_login_attempts" in df_clean.columns:
    df_clean = df_clean[df_clean["failed_login_attempts"] >= 0]

# request_rate no negativa
if "request_rate_per_min" in df_clean.columns:
    df_clean = df_clean[df_clean["request_rate_per_min"] >= 0]

print("Dimensiones luego de validar rangos:", df_clean.shape)

drop_cols = [
    "alert_id",
    "timestamp",
    "class_label",
    "priority_level",
    "risk_score"
]

existing_drop_cols = [col for col in drop_cols if col in df_clean.columns]

def definir_label(row):
    if row["severity"] in ["high", "critical"] or row["anomaly_score"] >= 0.7:
        return "malicioso"
    elif row["severity"] == "medium" or row["anomaly_score"] >= 0.4:
        return "investigar"
    else:
        return "benigno"

X = df_clean.drop(columns=existing_drop_cols + ["label"])

y = df_clean["label"]

print("Variables X:", X.shape)
print("Target y:", y.shape)

X_encoded = pd.get_dummies(X, drop_first=True)

print("Dimensiones luego de encoding:", X_encoded.shape)
display(X_encoded.head())

"""## Entrenamiento del modelo"""

cols_excluir = ["label", "attack_type", "attack_signature", "malware_indicator"]

X = df_clean.drop(columns=cols_excluir, errors="ignore")
y = df_clean["label"]

X_encoded = pd.get_dummies(X, drop_first=False)

print("Features:", X_encoded.shape)
print("Target distribution:")
print(y.value_counts())

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score, classification_report,
                              f1_score, confusion_matrix, ConfusionMatrixDisplay)
import matplotlib.pyplot as plt

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42, stratify=y)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=20,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    class_weight="balanced_subsample",
    n_jobs=-1
)

rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)

print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("F1 Macro:", f1_score(y_test, y_pred, average="macro"))
print(classification_report(y_test, y_pred,
      target_names=["Benigno", "A_Investigar", "Malicioso"]))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred, labels=rf_model.classes_)
disp = ConfusionMatrixDisplay(confusion_matrix=cm,
       display_labels=["Benigno", "A_Investigar", "Malicioso"])
disp.plot(cmap="Blues", xticks_rotation=45)
plt.show()

# Análisis FP — métrica clave de la tesis
fp_real      = (y_test == 0).sum()
fp_correctos = ((y_pred == 0) & (y_test == 0)).sum()
fp_escapados = ((y_pred != 0) & (y_test == 0)).sum()
falsa_alarma = ((y_pred == 0) & (y_test != 0)).sum()
print(f"\n── Detección de alertas benignas (FP del SOC) ──")
print(f"Benignas reales en test  : {fp_real}")
print(f"Detectadas correctamente : {fp_correctos} ({fp_correctos/fp_real*100:.1f}%)")
print(f"No detectadas            : {fp_escapados} ({fp_escapados/fp_real*100:.1f}%)")
print(f"Falsas alarmas           : {falsa_alarma}")

# Feature importance
feature_importance = pd.DataFrame({
    "feature"   : X_encoded.columns,
    "importance": rf_model.feature_importances_
}).sort_values("importance", ascending=False)

display(feature_importance.head(15))

top_features = feature_importance.head(15)
plt.figure(figsize=(10, 6))
plt.barh(top_features["feature"][::-1], top_features["importance"][::-1])
plt.title("Top 15 Variables Más Importantes")
plt.xlabel("Importancia")
plt.ylabel("Variable")
plt.tight_layout()
plt.show()

"""## Pruebas

### PRUEBA 1: Validación cruzada
"""

from sklearn.model_selection import StratifiedKFold, cross_validate

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scoring = ["accuracy", "f1_macro", "f1_weighted"]

cv_results = cross_validate(rf_model, X_encoded, y,
                            cv=cv, scoring=scoring,
                            n_jobs=-1, return_train_score=True)

print("── Validación Cruzada 5-fold ──")
for metric in scoring:
    val   = cv_results[f"test_{metric}"]
    train = cv_results[f"train_{metric}"]
    print(f"  {metric:<15} val: {val.mean():.4f} ± {val.std():.4f} | train: {train.mean():.4f}")

"""### PRUEBA 2: Curvas ROC por clase"""

from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt

classes   = [0, 1, 2]
nombres   = ["Benigno", "A_Investigar", "Malicioso"]
colores   = ["#1D9E75", "#7F77DD", "#D85A30"]

y_test_bin = label_binarize(y_test, classes=classes)
y_prob     = rf_model.predict_proba(X_test)

plt.figure(figsize=(8, 6))
for i, (nombre, color) in enumerate(zip(nombres, colores)):
    fpr, tpr, _ = roc_curve(y_test_bin[:, i], y_prob[:, i])
    roc_auc     = auc(fpr, tpr)
    plt.plot(fpr, tpr, color=color, lw=2,
             label=f"{nombre} (AUC = {roc_auc:.3f})")

plt.plot([0,1],[0,1], "k--", lw=1, label="Aleatorio (AUC = 0.5)")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Curvas ROC — Random Forest SOC")
plt.legend(loc="lower right")
plt.tight_layout()
plt.show()

"""### PRUEBA 3: Comparación con baseline"""

from sklearn.dummy import DummyClassifier
from sklearn.tree import DecisionTreeClassifier

baselines = {
    "Dummy (majority)"  : DummyClassifier(strategy="most_frequent", random_state=42),
    "Árbol de decisión" : DecisionTreeClassifier(max_depth=10, random_state=42),
    "Random Forest"     : rf_model,
}

print("\n── Comparación con modelos baseline ──")
print(f"{'Modelo':<22} {'Accuracy':>10} {'F1 Macro':>10} {'F1 Weighted':>12}")
print("-" * 58)

for nombre, modelo in baselines.items():
    if nombre != "Random Forest":
        modelo.fit(X_train, y_train)
    pred = modelo.predict(X_test)
    acc  = accuracy_score(y_test, pred)
    f1m  = f1_score(y_test, pred, average="macro")
    f1w  = f1_score(y_test, pred, average="weighted")
    print(f"{nombre:<22} {acc:>10.4f} {f1m:>10.4f} {f1w:>12.4f}")

"""### PRUEBA 4: Predicción con alertas de ejemplo"""

import joblib

# Mapeos necesarios (mismos que el pipeline de transformación)
MAP_EVENT_CATEGORY = {
    'lateralmovement':'lateral_movement','commandandcontrol':'command_and_control',
    'execution':'execution','initialaccess':'intrusion_attempt',
    'persistence':'persistence','privilegeescalation':'privilege_escalation',
    'defenseevasion':'evasion','credentialaccess':'credential_access',
    'discovery':'reconnaissance','collection':'data_collection',
    'exfiltration':'data_exfiltration','impact':'impact',
    'malware':'malware_activity','suspiciousactivity':'suspicious_activity',
}
MAP_TRAFFIC_TYPE = {
    'lateralmovement':'SMB','commandandcontrol':'HTTPS','execution':'HTTP',
    'initialaccess':'SSH','persistence':'HTTP','privilegeescalation':'RPC',
    'defenseevasion':'DNS','credentialaccess':'LDAP','discovery':'ICMP',
    'exfiltration':'DNS','impact':'TCP','suspiciousactivity':'TCP',
}
MAP_PROTOCOL = {
    'lateralmovement':'tcp','commandandcontrol':'tcp','initialaccess':'tcp',
    'exfiltration':'udp','discovery':'udp','impact':'tcp',
    'suspiciousactivity':'tcp','credentialaccess':'tcp',
}
MAP_MITRE_TACTIC = {
    'lateralmovement':'lateral movement','commandandcontrol':'command and control',
    'initialaccess':'initial access','exfiltration':'exfiltration',
    'impact':'impact','suspiciousactivity':'discovery',
    'credentialaccess':'credential access','discovery':'discovery',
}
MAP_KILL_CHAIN = {
    'lateralmovement':'lateral movement','commandandcontrol':'command & control',
    'initialaccess':'initial access','exfiltration':'exfiltration',
    'impact':'impact','suspiciousactivity':'unknown',
    'credentialaccess':'credential access',
}
MAP_ASSET = {
    'machine':'high','user':'medium','ip':'low','file':'low',
    'mailmessage':'low','cloudlogonrequest':'medium','mailcluster':'low',
}
MAP_IDS_ALERT  = {'suspicious':'suspicious pattern','malicious':'confirmed malicious indicator'}
MAP_FIREWALL   = {'suspicious':'monitored','incriminated':'blocked'}
MAP_SEVERITY   = {'suspicious':'medium','incriminated':'critical'}

def cat(c): return c.strip().lower().replace(' ','')

alertas_ejemplo = pd.DataFrame([
    {   # Alerta 1 — BenignPositive | CommandAndControl | SuspicionLevel=Suspicious
        "event_category"       : "command_and_control",
        "protocol"             : "tcp",
        "traffic_type"         : "https",
        "mitre_tactic"         : "command and control",
        "kill_chain_stage"     : "command & control",
        "failed_login_attempts": 0,
        "request_rate_per_min" : 20.0,
        "ids_ips_alert"        : "suspicious pattern",
        "asset_criticality"    : "high",
        "log_source"           : "edr",
        "firewall_action"      : "monitored",
        "severity"             : "medium",
    },
    {   # Alerta 2 — BenignPositive | SuspiciousActivity | SuspicionLevel=Suspicious
        "event_category"       : "suspicious_activity",
        "protocol"             : "tcp",
        "traffic_type"         : "tcp",
        "mitre_tactic"         : "discovery",
        "kill_chain_stage"     : "unknown",
        "failed_login_attempts": 0,
        "request_rate_per_min" : 20.0,
        "ids_ips_alert"        : "suspicious pattern",
        "asset_criticality"    : "high",
        "log_source"           : "edr",
        "firewall_action"      : "monitored",
        "severity"             : "medium",
    },
    {   # Alerta 3 — BenignPositive | Impact | sin SuspicionLevel
        "event_category"       : "impact",
        "protocol"             : "tcp",
        "traffic_type"         : "tcp",
        "mitre_tactic"         : "impact",
        "kill_chain_stage"     : "impact",
        "failed_login_attempts": 0,
        "request_rate_per_min" : 20.0,
        "ids_ips_alert"        : "unknown",
        "asset_criticality"    : "low",
        "log_source"           : "ips",
        "firewall_action"      : "unknown",
        "severity"             : "unknown",
    },
    {   # Alerta 4 — FalsePositive | Impact | sin SuspicionLevel
        "event_category"       : "impact",
        "protocol"             : "tcp",
        "traffic_type"         : "tcp",
        "mitre_tactic"         : "impact",
        "kill_chain_stage"     : "impact",
        "failed_login_attempts": 0,
        "request_rate_per_min" : 20.0,
        "ids_ips_alert"        : "unknown",
        "asset_criticality"    : "low",
        "log_source"           : "edr",
        "firewall_action"      : "unknown",
        "severity"             : "unknown",
    },
    {   # Alerta 5 — BenignPositive | Impact | DetectorId=72
        "event_category"       : "impact",
        "protocol"             : "tcp",
        "traffic_type"         : "tcp",
        "mitre_tactic"         : "impact",
        "kill_chain_stage"     : "impact",
        "failed_login_attempts": 0,
        "request_rate_per_min" : 20.0,
        "ids_ips_alert"        : "unknown",
        "asset_criticality"    : "low",
        "log_source"           : "ips",
        "firewall_action"      : "unknown",
        "severity"             : "unknown",
    },
    {   # Alerta 6 — TruePositive | InitialAccess | sin SuspicionLevel
        "event_category"       : "intrusion_attempt",
        "protocol"             : "tcp",
        "traffic_type"         : "ssh",
        "mitre_tactic"         : "initial access",
        "kill_chain_stage"     : "initial access",
        "failed_login_attempts": 0,
        "request_rate_per_min" : 20.0,
        "ids_ips_alert"        : "unknown",
        "asset_criticality"    : "medium",
        "log_source"           : "edr",
        "firewall_action"      : "unknown",
        "severity"             : "unknown",
    },
    {   # Alerta 7 — BenignPositive | Exfiltration | File
        "event_category"       : "data_exfiltration",
        "protocol"             : "udp",
        "traffic_type"         : "dns",
        "mitre_tactic"         : "exfiltration",
        "kill_chain_stage"     : "exfiltration",
        "failed_login_attempts": 0,
        "request_rate_per_min" : 20.0,
        "ids_ips_alert"        : "unknown",
        "asset_criticality"    : "low",
        "log_source"           : "edr",
        "firewall_action"      : "unknown",
        "severity"             : "unknown",
    },
    {   # Alerta 8 — TruePositive | InitialAccess | T1566 | User
        "event_category"       : "intrusion_attempt",
        "protocol"             : "tcp",
        "traffic_type"         : "ssh",
        "mitre_tactic"         : "initial access",
        "kill_chain_stage"     : "initial access",
        "failed_login_attempts": 0,
        "request_rate_per_min" : 20.0,
        "ids_ips_alert"        : "unknown",
        "asset_criticality"    : "medium",
        "log_source"           : "edr",
        "firewall_action"      : "unknown",
        "severity"             : "unknown",
    },
    {   # Alerta 9 — FalsePositive | Exfiltration | File | Private
        "event_category"       : "data_exfiltration",
        "protocol"             : "udp",
        "traffic_type"         : "dns",
        "mitre_tactic"         : "exfiltration",
        "kill_chain_stage"     : "exfiltration",
        "failed_login_attempts": 0,
        "request_rate_per_min" : 20.0,
        "ids_ips_alert"        : "unknown",
        "asset_criticality"    : "low",
        "log_source"           : "firewall",
        "firewall_action"      : "unknown",
        "severity"             : "unknown",
    },
    {   # Alerta 10 — BenignPositive | Impact | Ip | DetectorId=16
        "event_category"       : "impact",
        "protocol"             : "tcp",
        "traffic_type"         : "tcp",
        "mitre_tactic"         : "impact",
        "kill_chain_stage"     : "impact",
        "failed_login_attempts": 0,
        "request_rate_per_min" : 20.0,
        "ids_ips_alert"        : "unknown",
        "asset_criticality"    : "low",
        "log_source"           : "edr",
        "firewall_action"      : "unknown",
        "severity"             : "unknown",
    },
    {   # Alerta 11 — FalsePositive | Exfiltration | Ip | DetectorId=20
        "event_category"       : "data_exfiltration",
        "protocol"             : "udp",
        "traffic_type"         : "dns",
        "mitre_tactic"         : "exfiltration",
        "kill_chain_stage"     : "exfiltration",
        "failed_login_attempts": 0,
        "request_rate_per_min" : 20.0,
        "ids_ips_alert"        : "unknown",
        "asset_criticality"    : "low",
        "log_source"           : "edr",
        "firewall_action"      : "unknown",
        "severity"             : "unknown",
    },
    {   # Alerta 12 — TruePositive | InitialAccess | Ip | Private
        "event_category"       : "intrusion_attempt",
        "protocol"             : "tcp",
        "traffic_type"         : "ssh",
        "mitre_tactic"         : "initial access",
        "kill_chain_stage"     : "initial access",
        "failed_login_attempts": 0,
        "request_rate_per_min" : 20.0,
        "ids_ips_alert"        : "unknown",
        "asset_criticality"    : "low",
        "log_source"           : "edr",
        "firewall_action"      : "unknown",
        "severity"             : "unknown",
    },
    {   # Alerta 13 — FalsePositive | Exfiltration | MailMessage
        "event_category"       : "data_exfiltration",
        "protocol"             : "udp",
        "traffic_type"         : "dns",
        "mitre_tactic"         : "exfiltration",
        "kill_chain_stage"     : "exfiltration",
        "failed_login_attempts": 0,
        "request_rate_per_min" : 20.0,
        "ids_ips_alert"        : "unknown",
        "asset_criticality"    : "low",
        "log_source"           : "edr",
        "firewall_action"      : "unknown",
        "severity"             : "unknown",
    },
    {   # Alerta 14 — FalsePositive | InitialAccess | CloudLogonRequest
        "event_category"       : "intrusion_attempt",
        "protocol"             : "tcp",
        "traffic_type"         : "ssh",
        "mitre_tactic"         : "initial access",
        "kill_chain_stage"     : "initial access",
        "failed_login_attempts": 0,
        "request_rate_per_min" : 20.0,
        "ids_ips_alert"        : "unknown",
        "asset_criticality"    : "medium",
        "log_source"           : "edr",
        "firewall_action"      : "unknown",
        "severity"             : "unknown",
    },
    {   # Alerta 15 — FalsePositive | SuspiciousActivity | User | Private
        "event_category"       : "suspicious_activity",
        "protocol"             : "tcp",
        "traffic_type"         : "tcp",
        "mitre_tactic"         : "discovery",
        "kill_chain_stage"     : "unknown",
        "failed_login_attempts": 0,
        "request_rate_per_min" : 20.0,
        "ids_ips_alert"        : "unknown",
        "asset_criticality"    : "medium",
        "log_source"           : "edr",
        "firewall_action"      : "unknown",
        "severity"             : "unknown",
    },
])

labels_reales  = [0,0,0,0,0,2,0,2,0,0,0,2,0,0,0]
nombres_reales = [
    "BenignPositive","BenignPositive","BenignPositive","FalsePositive",
    "BenignPositive","TruePositive","BenignPositive","TruePositive",
    "FalsePositive","BenignPositive","FalsePositive","TruePositive",
    "FalsePositive","FalsePositive","FalsePositive"
]
nombres_clase = ["Benigno","A_Investigar","Malicioso"]

alertas_enc = pd.get_dummies(alertas_ejemplo, drop_first=False)
alertas_enc = alertas_enc.reindex(columns=X_encoded.columns, fill_value=0)

predicciones   = rf_model.predict(alertas_enc)
probabilidades = rf_model.predict_proba(alertas_enc)

print("\n── Predicción de alertas reales del GUIDE ──")
correctas = 0
for i, (pred, prob, real, grade) in enumerate(
        zip(predicciones, probabilidades, labels_reales, nombres_reales)):
    ok = "✓" if pred == real else "✗"
    if pred == real: correctas += 1
    print(f"\nAlerta {i+1:2} | Real: {grade:<20} | "
          f"Predicho: {nombres_clase[pred]:<14} | "
          f"Confianza: {max(prob)*100:.1f}% {ok}")
    print(f"           Benigno={prob[0]:.2f} | "
          f"A_Investigar={prob[1]:.2f} | Malicioso={prob[2]:.2f}")

print(f"\n── Resumen ──")
print(f"Correctas  : {correctas}/{len(predicciones)} "
      f"({correctas/len(predicciones)*100:.1f}%)")
print(f"Incorrectas: {len(predicciones)-correctas}/{len(predicciones)}")

"""## Exportar modelo"""

import joblib

artifact = {
    "model": rf_model,
    "training_columns": X_encoded.columns.tolist(),
    "target_classes": rf_model.classes_.tolist()
}

joblib.dump(artifact, "soc_model.pkl")
files.download("soc_model.pkl")