# Generated by Django 6.0.3 on 2026-04-15 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category', models.CharField(max_length=100)),
                ('attack_type', models.CharField(max_length=100)),
                ('attack_signature', models.CharField(max_length=200)),
                ('protocol', models.CharField(max_length=50)),
                ('traffic_type', models.CharField(max_length=100)),
                ('mitre_tactic', models.CharField(max_length=100)),
                ('kill_chain_stage', models.CharField(max_length=100)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('request_rate_per_min', models.FloatField(default=0.0)),
                ('ids_ips_alert', models.CharField(max_length=100)),
                ('malware_indicator', models.CharField(max_length=100)),
                ('asset_criticality', models.CharField(max_length=100)),
                ('log_source', models.CharField(max_length=100)),
                ('firewall_action', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
