# Generated by Django 6.0.3 on 2026-05-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_alert_ml_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='correlation_id',
            field=models.CharField(blank=True, default='unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='alert',
            name='evidence_role',
            field=models.CharField(blank=True, default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='has_threat_family',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='mitre_techniques',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='alert',
            name='os_family',
            field=models.CharField(blank=True, default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='attack_signature',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='alert',
            name='attack_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='malware_indicator',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
