# Generated by Django 6.0.3 on 2026-05-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_alert_correlation_id_alert_evidence_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='shap_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
