# Generated by Django 6.0.3 on 2026-05-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_add_shap_values_to_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='shap_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
