# Generated by Django 6.0.3 on 2026-05-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_add_shap_explanation_to_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='analyst_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alert',
            name='analyst_priority',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
