# Generated by Django 6.0.3 on 2026-05-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0008_add_analyst_priority_to_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='investigation_status',
            field=models.CharField(choices=[('new', 'Nueva'), ('investigating', 'En investigación'), ('investigated', 'Investigada'), ('false_positive', 'Falso positivo')], default='new', max_length=20),
        ),
    ]
