# Generated by Django 6.0.3 on 2026-05-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0012_alert_ml_evaluation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredictionLog',
        ),
    ]
