# Generated by Django 6.0.3 on 2026-08-07 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SIEMConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('splunk', 'Splunk Enterprise / Cloud'), ('sentinel', 'Microsoft Sentinel'), ('qradar', 'IBM QRadar'), ('elastic', 'Elastic Security'), ('wazuh', 'Wazuh'), ('cortex_xsiam', 'Cortex XSIAM (Palo Alto)')], max_length=20)),
                ('host', models.CharField(help_text='Host o IP del servidor, sin esquema (ej: localhost, splunk.miempresa.com)', max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('auth_type', models.CharField(choices=[('user_password', 'Usuario y contraseña'), ('bearer_token', 'Token (Bearer)')], default='user_password', max_length=20)),
                ('custom_query', models.TextField(blank=True)),
                ('batch_size', models.PositiveIntegerField(default=50)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('poll_interval_minutes', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('not_tested', 'No probado'), ('connected', 'Conectado'), ('error', 'Error de conexión')], default='not_tested', max_length=20)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_message', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conector SIEM',
                'verbose_name_plural': 'Conectores SIEM',
                'ordering': ['-created_at'],
            },
        ),
    ]
