# Generated by Django 6.0.3 on 2026-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siemconnector',
            name='extra_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='siemconnector',
            name='auth_type',
            field=models.CharField(choices=[('user_password', 'Usuario y contraseña'), ('bearer_token', 'Token (Bearer)'), ('api_key', 'API Key')], default='user_password', max_length=20),
        ),
    ]
