# Generated by Django 6.0.3 on 2026-08-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0002_siemconnector_extra_config_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siemconnector',
            options={'ordering': ['-created_at'], 'verbose_name': 'Conector SOC', 'verbose_name_plural': 'Conectores SOC'},
        ),
        migrations.AlterField(
            model_name='siemconnector',
            name='source_type',
            field=models.CharField(choices=[('splunk', 'Splunk Enterprise / Cloud'), ('sentinel', 'Microsoft Sentinel'), ('qradar', 'IBM QRadar'), ('elastic', 'Elastic Security'), ('wazuh', 'Wazuh'), ('cortex_xsiam', 'Cortex XSIAM (Palo Alto)'), ('crowdstrike', 'CrowdStrike Falcon Insight XDR'), ('defender_xdr', 'Microsoft Defender XDR'), ('cortex_xdr', 'Cortex XDR (Palo Alto)'), ('trendmicro', 'Trend Micro Vision One')], max_length=20),
        ),
    ]
