# Generated by Django 6.0.3 on 2026-08-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0003_alter_siemconnector_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siemconnector',
            name='last_test_message',
            field=models.TextField(blank=True),
        ),
    ]
