# Generated by Django 6.0.3 on 2026-08-10 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0004_alter_siemconnector_last_test_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestedSplunkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingested_events', to='connectors.siemconnector')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('connector', 'event_id'), name='unique_ingested_event_per_connector')],
            },
        ),
    ]
